import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const outfit = Outfit({ subsets: ["latin"] });

import Navbar from './_components/Navbar.jsx'

export const metadata: Metadata = {
  title: "Texi-GO | Book Texi Anywhere",
  description: "Generated by Umesh Tandon",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>
         
         <Navbar/>
         {children}
        
          


          </body>
      </html>
    </ClerkProvider>
  );
}
